### ISSUE TITLE
MS patches

### ISSUE THREAD

**Issue by Trass3r** [nathanchance/WSL2-Linux-Kernel#8]
Does this contain all the MS patches like their VMM integration?
https://devblogs.microsoft.com/commandline/memory-reclaim-in-the-windows-subsystem-for-linux-2/

**Comment by nathanchance** [comment]
Yes, it should. All of those patches are upstream now.

**Comment by Trass3r** [comment]
Ok interesting why do they still have a custom repo then. Only for the config?

**Comment by nathanchance** [comment]
They currently track LTS kernels, which up until the latest one (5.9) have not had all of the patches that they need. They just finished upgrading to 5.4 it seems so it will probably be a while before they upgrade to 5.9 and drop a lot of their patches. There are still some that they will carry out of tree because they are specific to WSL2 but I have picked all of those up.

**Comment by Trass3r** [comment]
> There are still some that they will carry out of tree because they are specific to WSL2 but I have picked all of those up.

That sounds good and answers my question.
